# Adapted from: https://github.com/satu0king/Github-Documentation-With-Doxygen
# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt update
        #sudo apt install -y quantum-espresso
        pip install codecov pytest pytest-cov pytest_mock
        #git clone --depth 1 -b stable_29Oct2020 https://github.com/lammps/lammps.git lammps
        #cp lammps_plugins/pair_mgp.* lammps/src
        #cd lammps/src
        #make -j 2 serial CCFLAGS='-std=c++11'
        #cd ../..
        #wget https://github.com/cp2k/cp2k/releases/download/v7.1.0/cp2k-7.1-Linux-x86_64.sopt
        #chmod u+x cp2k-7.1-Linux-x86_64.sopt
        pip install -r requirements.txt

    - name: Build
      run: |
        cd tests
        export PWSCF_COMMAND=pw.x
        export lmp=$(pwd)/../lammps/src/lmp_serial
        export CP2K_COMMAND=../cp2k-7.1-Linux-x86_64.sopt
        pytest
